export const ADD_MESSAGE_REQUEST = 'ADD_MESSAGE_REQUEST'
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const ADD_MESSAGE_ERROR = 'ADD_MESSAGE_ERROR'

export const UPDATE_USER_MEDIA_ALLOWED = 'UPDATE_USER_MEDIA_ALLOWED'

export const PLAY_MY_VIDEO = 'PLAY_MY_VIDEO'
export const START_MY_VIDEO = 'START_MY_VIDEO'
export const STOP_MY_VIDEO = 'STOP_MY_VIDEO'

export const PLAY_YOUTUBE_VIDEO = 'PLAY_YOUTUBE_VIDEO'
export const PAUSE_YOUTUBE_VIDEO = 'PAUSE_YOUTUBE_VIDEO'
export const STOP_YOUTUBE_VIDEO = 'STOP_YOUTUBE_VIDEO'
export const SET_YOUTUBE_READY = 'SET_YOUTUBE_READY'

export const START_YOUTUBE_SEARCH = 'START_YOUTUBE_SEARCH'
export const RECIEVE_YOUTUBE_SEARCH = 'RECIEVE_YOUTUBE_SEARCH'
export const ERROR_YOUTUBE_SEARCH = 'ERROR_YOUTUBE_SEARCH'

export const RECIEVE_USER = 'RECIEVE_USER'
